var Soals = [
	"Identifikasi bakat & kompetensi murid",
	"Memberikan Arahan",
	"Memahami perilaku siswa",
	"Menggali kebutuhan siswa",
	"Analisa kebutuhan siswa",
	"Observasi kelas",
	"Membangun hubungan positif",
	"Metode pengajaran kreatif",
	"Metode pengajaran tematik",
	"Menentukan target & tujuan",
	"Menentukan pengalaman belajar",
	"Menentukan materi",
	"Membangun konsep",
	"Memonitor perkembangan & melakukan assesment",
	"Key Performance Indicator",
	"Prinsip perancangan pembelajaran",
	"Mengembangkan komponen rancangan",
	"Mentoring",
	"Mempersiapkan handout dan tools",
	"Mengambil keputusan transaksional",
	"Memanfaatkan teknologi informasi",
	"Memotivasi",
	"Berkomunikasi secara efektif",
	"Memfasilitasi diskusi",
	"Menyarankan secara positif",
	"Memfasilitasi group",
	"Merespon secara positif",
	"Meningkatkan kemampuan sosial",
	"Membuat laporan professional",
	"Mendemonstrasikan pengetahuan",
	"Menganalisa hasil pembelajaran",
	"Berkoordinasi dengan tim kerja",
	"Memecahkan masalah",
	"Mengoptimalkan sumber daya",
	"Menyelesaikan konflik",
	"Mengelola administrasi",
	"Memahami visi dan misi",
	"Mengkondisikan lingkungan kerja",
	"Membuat gagasan baru",
	"Berpikir Out Of The Box",
	"Mengambil keputusan",
	"Memahami kondisi siswa",
	"Mengarahkan potensi",
	"Menangani keberatan",
	"Menangani penolakan"
];